EPOCHS = 10
INPUT_SIZE = 50
HIDDEN_SIZE = 100
BATCH_SIZE = 10
LEARNING_RATE = 0.9

STATE_FILE = ""
WORD_TO_VECTOR_FILE = ""
TRAIN_SET_FILE = ""
VALID_SET_FILE = ""
VALID_PRECISION_FILE = ""
LOSS_FILE = ""
